### ISSUE TITLE
Make titles optional

### ISSUE THREAD

**Issue by atmoio** [standardnotes/iOS#10]
Notes for mobile can sometimes be just quick thoughts. Having a title slows things down.

UI:

[Nav Bar]
[Add title button]
[Editor]

**Comment by jz709u** [comment]
also instead of adding a add title button why don't we just have a watermarked text inside of the textfield saying "Add Title" and keep the Textfield initially empty?

![simulator screen shot jan 19 2017 17 51 08](https://cloud.githubusercontent.com/assets/19835598/22099747/f0e73aca-de6f-11e6-811c-906aa3bbb459.png)

**Comment by atmoio** [comment]
Hmm that works too. Easier to implement too, which means less complexity, more longevity :)
