### ISSUE TITLE
Sort notes by created_at/updated_at option

### ISSUE THREAD

**Issue by dannysu** [standardnotes/iOS#32]
Would love to have a "Sort by date updated" on the iOS app just like the desktop app.
Seems like a non-intrusive addition that still keeps the app minimal, but usable.
Thanks!

**Comment by atmoio** [comment]
Seems reasonable.

**Comment by jz709u** [comment]
We don't update the date on each note when we modify a note.  Shouldn't the notes be listed by updated date by default?  So the top of the list is always the most recently updated note or created note

**Comment by atmoio** [comment]
Well when we save a note, we merge the response of saved_items, which updates the modified date.

Notes are currently sorted by the date they were created. On Web, user can choose between sorting by most recently updated OR newly created. 

I haven't yet thought of the UI for this, but I'm thinking two options:
1. Change the "Tags" button on the top left to a "Filter" button, which brings up the filter screen which allows you to specify tags and also sort order.
2. Add a sort button to the right of the search bar in the notes list. This might be the better, simpler option, but I'm not sure of a standard UI for this. Maybe button then action sheet on click.

**Comment by jimmykaiser** [comment]
What are the use cases for sorting by date created? The current sort means that notes remain in the order in which they were created, with new notes added to the top of the list. 

I can think of a couple use cases for sorting by date updated by default: 
* As the user, I can see the notes I most recently edited at the top of the list so that I can pick up where I left off. 
* I can quickly move a note to the top of the list by updating it, if I want to remind myself to look at it later. 

The reason why I ask is it _looks_ like a one-line change to the `NSSortDescriptor()` function would make it sort by date updated. Which I can happily propose in a pull request if you agree with my reasoning.

**Comment by atmoio** [comment]
Let's see how this does: https://twitter.com/StandardNotes/status/858081402277031936

**Comment by atmoio** [comment]
ac15766d5527cc75eb0160ccad2314912ada1790

Submitted to App Store.
